"use strict";

/* The counters, read back, for whoever knows the password.
 *
 * The password is never in this repo and never in the browser. What is
 * deployed is a scrypt hash of it in an environment variable, generated by
 * `node tools/admin-hash.js` on the machine of whoever owns the site. That
 * matters beyond good practice here: this repository is public, so anything
 * checked in is published.
 *
 * Three things guard it, and none of them is the admin page:
 *
 *   scrypt, at a cost that takes about a tenth of a second. That is nothing
 *   once and ruinous a billion times, which is the whole point of a password
 *   hash and the reason a plain SHA-256 would not do.
 *
 *   timingSafeEqual, so a wrong answer takes the same time whether the first
 *   character was right or not.
 *
 *   A signed token afterwards, valid for two hours, so a session is one
 *   password check rather than one per request. It is an HMAC over its own
 *   expiry - there is no session list to keep, and nothing to steal from the
 *   server that is not already the server.
 *
 * The admin page is a viewer. It cannot let anyone in, because it is not what
 * is being asked.
 */

const crypto = require("crypto");
const { configured, pipeline, foundVars } = require("./_store");

const HASH = process.env.ADMIN_HASH || "";
const TOKEN_LIFE = 2 * 60 * 60 * 1000;

const json = (res, code, body) => {
  res.statusCode = code;
  res.setHeader("Content-Type", "application/json");
  res.setHeader("Cache-Control", "no-store");
  res.end(JSON.stringify(body));
};

/* scrypt$<N>$<r>$<p>$<saltB64>$<hashB64> */
function checkPassword(given) {
  const parts = HASH.split("$");
  if (parts.length !== 6 || parts[0] !== "scrypt") return false;
  const N = Number(parts[1]), r = Number(parts[2]), p = Number(parts[3]);
  if (!(N > 1) || !(r > 0) || !(p > 0)) return false;
  let salt, want;
  try {
    salt = Buffer.from(parts[4], "base64");
    want = Buffer.from(parts[5], "base64");
  } catch { return false; }
  let got;
  try {
    got = crypto.scryptSync(String(given), salt, want.length, { N, r, p, maxmem: 256 * 1024 * 1024 });
  } catch { return false; }
  return got.length === want.length && crypto.timingSafeEqual(got, want);
}

/* The deployed hash is the only secret there is, so it is also the key the
   token is signed with. Knowing a token tells you nothing about the password;
   the hash is not reversible and never leaves the server. */
const sign = (exp) => crypto.createHmac("sha256", HASH).update(String(exp)).digest("base64url");

function tokenFor() {
  const exp = Date.now() + TOKEN_LIFE;
  return exp + "." + sign(exp);
}

function tokenValid(tok) {
  const s = String(tok || "");
  const dot = s.indexOf(".");
  if (dot < 1) return false;
  const exp = Number(s.slice(0, dot));
  if (!isFinite(exp) || exp < Date.now()) return false;
  const want = Buffer.from(sign(exp));
  const got = Buffer.from(s.slice(dot + 1));
  return got.length === want.length && crypto.timingSafeEqual(got, want);
}

const dayList = (n) => {
  const out = [];
  const d = new Date();
  for (let i = 0; i < n; i++) {
    out.push(new Date(d.getTime() - i * 86400000).toISOString().slice(0, 10));
  }
  return out;
};

/* A day is one hash: pv, and then prefixed fields saying what they count.
 *
 *   p:  the page       r:  the site it was reached from
 *   g:  the country    u:  the browser family        d:  the screen
 *
 * Anything with a prefix this does not know is skipped, so a field added
 * later cannot break a reader deployed before it.
 *
 * Upstash returns a hash as an object; some versions return the flat
 * [field, value, field, value] list Redis itself uses. Both are accepted,
 * because being wrong about which costs a silently empty page. */
function fieldsOf(raw) {
  const out = new Map();
  if (!raw) return out;
  if (Array.isArray(raw)) {
    for (let i = 0; i + 1 < raw.length; i += 2) out.set(String(raw[i]), Number(raw[i + 1]) || 0);
  } else if (typeof raw === "object") {
    for (const k of Object.keys(raw)) out.set(k, Number(raw[k]) || 0);
  }
  return out;
}

const sorted = (m) => [...m.entries()]
  .map(([name, n]) => ({ name, n })).sort((a, b) => b.n - a.n);

module.exports = async function handler(req, res) {
  if (req.method !== "POST") return json(res, 405, { error: "POST only" });
  if (!HASH) {
    return json(res, 503, { error: "No ADMIN_HASH is set on this deployment. " +
      "Run node tools/admin-hash.js and put the result in the environment." });
  }

  let body = req.body;
  if (typeof body === "string") { try { body = JSON.parse(body); } catch { body = null; } }
  body = body || {};

  let token = body.token;
  if (!tokenValid(token)) {
    /* Every wrong answer costs the same tenth of a second scrypt takes, and
       the reply says nothing about which part was wrong. */
    if (!body.password || !checkPassword(body.password)) {
      return json(res, 401, { error: "Wrong password." });
    }
    token = tokenFor();
  }

  if (!configured()) {
    /* Which names were found, so "it is not counting" can be diagnosed from
       the page rather than by guessing. Names only, never values. */
    return json(res, 200, { token, configured: false, days: [], found: foundVars() });
  }

  /* One command per day, rather than six. Reading sixty days used to be three
     hundred and sixty commands every time this page was opened, which on a
     store billed per command is the expensive half of the whole feature. */
  const days = dayList(Math.min(400, Math.max(1, Number(body.days) || 60)));
  let out;
  try {
    out = await pipeline(days.map((d) => ["HGETALL", "mu:d:" + d]));
  } catch (e) {
    return json(res, 502, { token, error: "The counter store did not answer." });
  }

  const PREFIX = { "p:": new Map(), "r:": new Map(), "g:": new Map(), "u:": new Map(), "d:": new Map() };
  const perDay = [];

  (out || []).forEach((raw, i) => {
    const fields = fieldsOf(raw);
    perDay.push({ day: days[i], views: fields.get("pv") || 0 });
    for (const [field, n] of fields) {
      const bucket = PREFIX[field.slice(0, 2)];
      if (!bucket) continue;                        // "pv", or something newer
      const name = field.slice(2);
      bucket.set(name, (bucket.get(name) || 0) + n);
    }
  });

  return json(res, 200, {
    token,
    configured: true,
    days: perDay,
    total: perDay.reduce((a, b) => a + b.views, 0),
    pages: sorted(PREFIX["p:"]).slice(0, 60),
    referrers: sorted(PREFIX["r:"]).slice(0, 40),
    countries: sorted(PREFIX["g:"]).slice(0, 40),
    browsers: sorted(PREFIX["u:"]),
    devices: sorted(PREFIX["d:"]),
  });
};
