"use strict";

/* The counters, read back, for whoever knows the password.
 *
 * The password is never in this repo and never in the browser. What is
 * deployed is a scrypt hash of it in an environment variable, generated by
 * `node tools/admin-hash.js` on the machine of whoever owns the site. That
 * matters beyond good practice here: this repository is public, so anything
 * checked in is published.
 *
 * Three things guard it, and none of them is the admin page:
 *
 *   scrypt, at a cost that takes about a tenth of a second. That is nothing
 *   once and ruinous a billion times, which is the whole point of a password
 *   hash and the reason a plain SHA-256 would not do.
 *
 *   timingSafeEqual, so a wrong answer takes the same time whether the first
 *   character was right or not.
 *
 *   A signed token afterwards, valid for two hours, so a session is one
 *   password check rather than one per request. It is an HMAC over its own
 *   expiry - there is no session list to keep, and nothing to steal from the
 *   server that is not already the server.
 *
 * The admin page is a viewer. It cannot let anyone in, because it is not what
 * is being asked.
 */

const crypto = require("crypto");
const { configured, pipeline, foundVars } = require("./_store");

const HASH = process.env.ADMIN_HASH || "";
const TOKEN_LIFE = 2 * 60 * 60 * 1000;

const json = (res, code, body) => {
  res.statusCode = code;
  res.setHeader("Content-Type", "application/json");
  res.setHeader("Cache-Control", "no-store");
  res.end(JSON.stringify(body));
};

/* scrypt$<N>$<r>$<p>$<saltB64>$<hashB64> */
function checkPassword(given) {
  const parts = HASH.split("$");
  if (parts.length !== 6 || parts[0] !== "scrypt") return false;
  const N = Number(parts[1]), r = Number(parts[2]), p = Number(parts[3]);
  if (!(N > 1) || !(r > 0) || !(p > 0)) return false;
  let salt, want;
  try {
    salt = Buffer.from(parts[4], "base64");
    want = Buffer.from(parts[5], "base64");
  } catch { return false; }
  let got;
  try {
    got = crypto.scryptSync(String(given), salt, want.length, { N, r, p, maxmem: 256 * 1024 * 1024 });
  } catch { return false; }
  return got.length === want.length && crypto.timingSafeEqual(got, want);
}

/* The deployed hash is the only secret there is, so it is also the key the
   token is signed with. Knowing a token tells you nothing about the password;
   the hash is not reversible and never leaves the server. */
const sign = (exp) => crypto.createHmac("sha256", HASH).update(String(exp)).digest("base64url");

function tokenFor() {
  const exp = Date.now() + TOKEN_LIFE;
  return exp + "." + sign(exp);
}

function tokenValid(tok) {
  const s = String(tok || "");
  const dot = s.indexOf(".");
  if (dot < 1) return false;
  const exp = Number(s.slice(0, dot));
  if (!isFinite(exp) || exp < Date.now()) return false;
  const want = Buffer.from(sign(exp));
  const got = Buffer.from(s.slice(dot + 1));
  return got.length === want.length && crypto.timingSafeEqual(got, want);
}

const dayList = (n) => {
  const out = [];
  const d = new Date();
  for (let i = 0; i < n; i++) {
    out.push(new Date(d.getTime() - i * 86400000).toISOString().slice(0, 10));
  }
  return out;
};

/* A sorted set comes back as a flat [member, score, member, score] list. */
function pairs(flat, limit) {
  const out = [];
  for (let i = 0; i + 1 < (flat || []).length; i += 2) {
    out.push({ name: String(flat[i]), n: Number(flat[i + 1]) || 0 });
  }
  out.sort((a, b) => b.n - a.n);
  return limit ? out.slice(0, limit) : out;
}

function merge(rows) {
  const total = new Map();
  for (const flat of rows) {
    for (const { name, n } of pairs(flat)) total.set(name, (total.get(name) || 0) + n);
  }
  return [...total.entries()].map(([name, n]) => ({ name, n })).sort((a, b) => b.n - a.n);
}

module.exports = async function handler(req, res) {
  if (req.method !== "POST") return json(res, 405, { error: "POST only" });
  if (!HASH) {
    return json(res, 503, { error: "No ADMIN_HASH is set on this deployment. " +
      "Run node tools/admin-hash.js and put the result in the environment." });
  }

  let body = req.body;
  if (typeof body === "string") { try { body = JSON.parse(body); } catch { body = null; } }
  body = body || {};

  let token = body.token;
  if (!tokenValid(token)) {
    /* Every wrong answer costs the same tenth of a second scrypt takes, and
       the reply says nothing about which part was wrong. */
    if (!body.password || !checkPassword(body.password)) {
      return json(res, 401, { error: "Wrong password." });
    }
    token = tokenFor();
  }

  if (!configured()) {
    /* Which names were found, so "it is not counting" can be diagnosed from
       the page rather than by guessing. Names only, never values. */
    return json(res, 200, { token, configured: false, days: [], found: foundVars() });
  }

  const days = dayList(Math.min(400, Math.max(1, Number(body.days) || 60)));
  const cmds = [];
  for (const d of days) cmds.push(["GET", "mu:pv:" + d]);
  for (const d of days) cmds.push(["ZRANGE", "mu:path:" + d, 0, -1, "WITHSCORES"]);
  for (const d of days) cmds.push(["ZRANGE", "mu:ref:" + d, 0, -1, "WITHSCORES"]);
  for (const d of days) cmds.push(["ZRANGE", "mu:geo:" + d, 0, -1, "WITHSCORES"]);
  for (const d of days) cmds.push(["ZRANGE", "mu:ua:" + d, 0, -1, "WITHSCORES"]);
  for (const d of days) cmds.push(["ZRANGE", "mu:dev:" + d, 0, -1, "WITHSCORES"]);

  let out;
  try { out = await pipeline(cmds); } catch (e) {
    return json(res, 502, { token, error: "The counter store did not answer." });
  }

  const n = days.length;
  const slice = (i) => out.slice(i * n, (i + 1) * n);
  const views = slice(0).map((v) => Number(v) || 0);

  return json(res, 200, {
    token,
    configured: true,
    days: days.map((d, i) => ({ day: d, views: views[i] })),
    total: views.reduce((a, b) => a + b, 0),
    pages: merge(slice(1)).slice(0, 60),
    referrers: merge(slice(2)).slice(0, 40),
    countries: merge(slice(3)).slice(0, 40),
    browsers: merge(slice(4)),
    devices: merge(slice(5)),
  });
};
